### ISSUE TITLE
Please help with the categorizing

### ISSUE THREAD

**Issue by scao1** [UBC-MDS/DSCI522_group315#18]
Could you help me with grouping the selected features? For the 11 selected features, which group do they belong to?
Our 11 selected features: 

1. sig_str_att
2. head_att
3. total_str_att
4. td_att
5. distance_att
6. distance_landed
7. pass
8. total_str_landed
9. td_pct
10. td_landed
11. ground_att

The categories:
1. Striking/Grappling : Feature 1, 3, 8
2. Aggressiveness
3. Cage/Ring Control

**Comment by SamEdwardes** [comment]
Hey Subing, sorry I did not see this until now. I would group into three different categories:

```
striking_features <- c("sig_str_att", "sig_str_landed", "sig_str_pct",
  "total_str_att", "total_str_landed")

ground_features <- c("td_att", "td_landed", "td_pct", "sub_att", "pass", "rev")

attacks_to_features <- c("head_att", "head_landed", "body_att", "body_landed",
  "leg_att", "leg_landed")

attacks_from_features <- c("distance_att", "distance_landed", "clinch_att",
  "clinch_landed", "ground_att", "ground_landed")
```

From this we would have to make assumptions to link back to the three categories you suggest.

1. Striking/grappling would include `striking_features` and `ground_features`. This is the most clear connection in my mind.
2. Aggressiveness could be inferred from the the volume of strikes or attacks they are performing. However we have lost this level of detail at the moment because we are only using proportion. So at this stage I would just associate aggressiveness with being related to a higher proportion of a category.
3. Cage/ring control is the hardest. None of these clearly tell us that. Again I think we just infer that a higher proportion also shows octagon control. To really capture this we would need positional data (e.g. time spent walking backwards vs. forwards.)

I hope this help... I know it is probably not exactly what you were looking for.

**Comment by scao1** [comment]
Thank you for your detailed explanation! It helps!
