### ISSUE TITLE
[IMPORTANT] EDA does not run

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI522_group315#25]
```
Warning message:
package 'docopt' was built under R version 3.6.2
Warning message:
package 'GGally' was built under R version 3.6.2
[1] "Loading DataFrame..."
[1] "Creating plots..."
Saving 7 x 7 in image
[1] "Created correlation plot..."
Saving 7 x 7 in image
Error in pivot_longer(., cols = -{ :
  could not find function "pivot_longer"
Calls: main ... withVisible -> eval -> eval -> _fseq -> freduce -> <Anonymous>
In addition: Warning message:
In GGally::ggcorr(df, size = 3, hjust = 0.85, layout.exp = 2) :
  data in column(s) 'winner' are not numeric and were ignored
Execution halted
```

**Comment by ksedivyhaley** [comment]
Never mind, it looks like I had for some reason updated my tidyverse without updating tidyr.

**Comment by SamEdwardes** [comment]
Thanks Kate. It looks like your `tidyr` package may be out of date. I believe that is where the `pivot_longer` function is from.

We listed dependencies in our README:

>  docopt==0.6.1
> tidyverse==1.2.1
>  janitor==1.2.0
>  GGally==1.4.0
>  kableExtra==1.1.0
>  knitr==1.27.2

I think the issue is `tidyverse==1.2.0` should be `1.3.0`. Sorry about this confusion! We will double check our requirements.

**Comment by ksedivyhaley** [comment]
Hi Sam, I'm assuming you were drafting this when I posted my last response - this appears to have been my error with the dependencies!
