### ISSUE TITLE
feedback 

### ISSUE THREAD

**Issue by scao1** [UBC-MDS/DSCI522_group315#32]
1. Figure 2 is very crowded and the labels is hard to see.
2. Include ROC curve, f1 score etc.

**Comment by sweber15** [comment]
Thank you for the feedback. Feedback is compiled in issue #35

**Comment by SamEdwardes** [comment]
Please not we have chosen to not include ROC curve of F1 score. This is because the purpose of our analysis is not to achieve an accurate prediction model. The purpose of our analysis was to build an interpretable model to assess if the UFC judging is fair. If we were able to build an accurate model, this would support the hypothesis that the UFC is fair. If we are unable to build an accurate model, it would support the hypothesis that the UFC is not fair because the judges to not consistently award the same behaviour.

Because of our approach, we feel that metricizes such as ROC curve and F1 score are not relevant.
